<a href="https://colab.research.google.com/github/RuthCMoreno/Diplomado_IA/blob/main/S8_C2_NN_keras_Fashion.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# NumPy nos permite realizar operaciones de álgebra lineal, matrices y es muy flexible para ser utilizada con TensorFlow
import numpy as np

# Matplotlib simplifica la creación de gráficos y será muy importante para presentar los resultados obtenidos
import matplotlib.pyplot as plt

# Instalamos TensorFlow en nuestro entorno de ejecución
import tensorflow as tf

# Keras es una serie de APIs de TensorFlow que permiten simplificar el desarrollo de modelos
from tensorflow import keras

In [2]:
datos = keras.datasets.fashion_mnist

In [3]:
# Almacenamos la información de la base de datos y la dividimos en conjuntos de prueba y entrenamiento.
# X_train, y_train,                               X_test, y_test
(imagenes_entrenamiento, labels_entrenamiento), (imagenes_prueba, labels_prueba) = datos.load_data()

# Dado que las imágenes tienen una descripción numérica, es mucho más sencillo revisarlas por su nombre
# Clase_imagenes = [0 , 1,   2, ]
clase_imagenes = ['Playera', 'Pantalón', 'Suéter', 'Vestido', 'Abrigo', 'Sandalia', 'Camisa', 'Tenis', 'Bolso', 'Botas']

29515/29515 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step
26421880/26421880 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step
5148/5148 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step
4422102/4422102 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step


In [4]:
imagenes_prueba[20]

array([[  0,   0,   0,   0,   0,   0,   0,   0,  24, 173, 222, 224, 206,
        180, 235, 175, 185, 233, 233, 149,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   1,   0,   0,  22, 139, 242, 215, 252, 229, 211,
        112,   0,  52, 139, 228, 248, 202, 211, 158,  17,   0,   0,   0,
          0,   0],
       [  0,   0,   1,   0,   0, 143, 230, 229, 208, 197, 242, 224, 214,
        234, 186, 255, 234, 223, 235, 199, 211, 237, 219,  48,   0,   0,
          0,   0],
       [  0,   0,   0,   0, 133, 216, 219, 205, 205, 185, 216, 202, 186,
        180, 199, 192, 225, 238, 182, 197, 222, 220, 208, 194,  29,   0,
          1,   0],
       [  0,   3,   0,  26, 214, 186, 208, 206, 209, 202, 194, 206, 195,
        173, 185, 181, 224, 177, 199, 195, 199, 215, 182, 208, 186,   0,
          0,   0],
       [  0,   7,   0, 126, 211, 185, 214, 215, 211, 213, 209, 197, 196,
        224, 200, 211, 194, 210, 222, 227, 232, 218, 185, 191, 199,   7,
          0,   0],
       [  0,   0,   0, 183, 205, 182, 201, 190, 211, 204, 209, 214, 202,
        209, 196, 192, 194, 195, 192, 189, 219, 227, 180, 178, 210, 121,
          0,   0],
       [  0,   0,  48, 191, 189, 178, 235, 195, 192, 196, 183, 187, 189,
        189, 187, 187, 187, 189, 183, 182, 191, 187, 175, 186, 190, 182,
          0,   0],
       [  0,   0, 130, 182, 176, 183, 205, 185, 191, 190, 180, 187, 185,
        200, 189, 190, 195, 196, 200, 195, 199, 196, 191, 173, 180, 185,
          0,   0],
       [  0,   0, 158, 189, 173, 197, 172, 200, 201, 187, 205, 194, 180,
        182, 182, 173, 191, 194, 182, 192, 192, 195, 194, 181, 194, 210,
         13,   0],
       [  0,   0, 157, 185, 191, 180, 186, 185, 187, 185, 195, 201, 199,
        190, 187, 187, 204, 182, 200, 185, 206, 202, 177, 186, 166, 183,
         52,   0],
       [  0,   0, 195, 173, 180, 205, 186, 192, 201, 200, 192, 189, 197,
        204, 200, 191, 173, 180, 195, 205, 205, 200, 202, 163, 143, 197,
         72,   0],
       [  0,   0, 210, 170, 167, 178, 196, 215, 204, 204, 206, 205, 200,
        192, 181, 190, 175, 190, 199, 196, 195, 181, 158, 177, 152, 190,
         87,   0],
       [  0,   0, 197, 171, 178, 147, 114, 215, 177, 145, 156, 168, 161,
        157, 170, 164, 175, 154, 150, 162, 192, 129, 107, 190, 158, 197,
        120,   0],
       [  0,   5, 192, 166, 186, 164,  81, 210, 173, 150, 172, 162, 178,
        157, 166, 176, 176, 166, 171, 167, 196, 139,  90, 185, 157, 187,
        111,   0],
       [  0,  25, 177, 159, 180, 142,  64, 204, 178, 168, 180, 158, 164,
        166, 162, 178, 163, 156, 177, 164, 211, 140,  85, 210, 153, 170,
        129,   0],
       [  0,  36, 182, 164, 197, 142,  86, 215, 167, 158, 154, 163, 181,
        175, 164, 159, 167, 159, 177, 162, 200, 144,  95, 199, 145, 190,
        140,   0],
       [  0,  38, 173, 153, 172, 121,  72, 215, 154, 166, 161, 163, 181,
        172, 170, 171, 168, 164, 175, 168, 187, 140,  65, 164, 143, 170,
        123,   0],
       [  0,  29, 173, 144, 162, 112,  64, 219, 167, 176, 181, 167, 180,
        178, 166, 171, 171, 167, 183, 182, 204, 150,  43, 171, 134, 162,
        119,   0],
       [  0,  24, 164, 139, 175, 111,  59, 200, 163, 153, 150, 137, 144,
        142, 145, 147, 156, 138, 138, 137, 163, 138,  36, 186, 139, 154,
        124,   0],
       [  0,  25, 181, 138, 167, 109,  55, 178, 142, 140, 143, 145, 135,
        143, 145, 150, 137, 138, 161, 152, 159, 131,  40, 201, 123, 164,
        129,   0],
       [  0,   0, 161, 143, 163, 133,  39, 185, 153, 152, 145, 154, 147,
        152, 140, 133, 153, 148, 152, 139, 156, 166,  31, 168, 126, 159,
        110,   0],
       [  0,   0, 173, 138, 154, 126,  32, 194, 140, 149, 139, 138, 139,
        138, 154, 135, 158, 149, 162, 152, 168, 133,  15, 183, 138, 163,
        116,   0],
       [  0,   0, 166, 145, 149, 126,   0, 204, 164, 133, 159, 154, 156,
        152, 149, 167, 156, 143, 150, 129, 194, 129,  16, 199, 137, 159,
        117,   0],
       [  0,   0, 137, 163, 143, 139,   

In [5]:
labels_prueba[20]

np.uint8(2)

In [6]:
print(imagenes_entrenamiento.shape)
print(labels_entrenamiento.shape)

(60000, 28, 28)
(60000,)


In [7]:
print(imagenes_prueba.shape)
print(labels_prueba.shape)

(10000, 28, 28)
(10000,)


# Modelo: red neuronal

In [8]:
from keras.models import Sequential
from keras import layers


In [12]:
#Arquitectura
modelo = Sequential([
    layers.Flatten(input_shape=(28, 28)), #es la forma de los datos de entrada
    layers.Dense(128, activation='relu'), #esto porque siempre maneja datos positivos porque está manejando colores que van de 0 a 255
    layers.Dense(10, activation='softmax') #le pongo 10 porque tengo 10 tipos de ropa, la capa de salida en problemas de clasificación tiene tantas neuronas como número de clases
])

/usr/local/lib/python3.11/dist-packages/keras/src/layers/reshaping/flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [13]:
modelo.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])  #compile son los hiperparámetros

modelo.fit(imagenes_entrenamiento, labels_entrenamiento, epochs=12) #fit es ajuste, entrenamiento

Epoch 1/12
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - accuracy: 0.6725 - loss: 11.5704
Epoch 2/12
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - accuracy: 0.7715 - loss: 0.6556
Epoch 3/12
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - accuracy: 0.7897 - loss: 0.5785
Epoch 4/12
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - accuracy: 0.8054 - loss: 0.5450
Epoch 5/12
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - accuracy: 0.8230 - loss: 0.5065
Epoch 6/12
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - accuracy: 0.8246 - loss: 0.4962
Epoch 7/12
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - accuracy: 0.8322 - loss: 0.4855
Epoch 8/12
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - accuracy: 0.8354 - loss: 0.4705
Epoch 9/12
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - accuracy: 0.8367 - loss: 0.4785
Epoch 10/12
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - accuracy: 0.8416 - loss: 0.4622
Epoch 11/12
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - accuracy: 0.8415 - loss: 0.4557
Epoch 12/12
1875/1875 

In [14]:
predicciones = modelo.predict(imagenes_prueba)
predicciones.shape

313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step


(10000, 10)

In [15]:
imagenes_prueba[200]
predicciones[200]

array([2.57308193e-06, 9.99928415e-01, 1.51124107e-06, 6.42338709e-05,
       3.12745169e-06, 9.77159873e-24, 1.18517765e-14, 0.00000000e+00,
       2.42009062e-08, 0.00000000e+00], dtype=float32)

In [16]:
np.round(predicciones[200])

array([0., 1., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)

In [18]:
# Predicciones redondeadas
prediccion = np.round(predicciones[200])
# Buscamos la posición que tiene el argumento máximo
posicion = np.argmax(prediccion)
posicion

np.int64(1)

In [19]:
clase_imagenes = ['Playera', 'Pantalón', 'Suéter', 'Vestido', 'Abrigo', 'Sandalia', 'Camisa', 'Tenis', 'Bolso', 'Botas']
clase_imagenes[posicion]

'Pantalón'

In [23]:
numero_Imagen = 570
#print(imagenes_prueba[numero_Imagen])
# Predicciones redondeadas
prediccion = np.round(predicciones[numero_Imagen])
posicion = np.argmax(prediccion)
clase_imagenes = ['Playera', 'Pantalón', 'Suéter', 'Vestido', 'Abrigo', 'Sandalia', 'Camisa', 'Tenis', 'Bolso', 'Botas']
print('La imagen de prueba numero '+ str(numero_Imagen) + ' es:')
clase_imagenes[posicion]
imagenes_prueba[numero_Imagen]

La imagen de prueba numero 570 es:


array([[  0,   0,   0,   0,   0,   0,   0,   0,   1,   0,   0,   0,  62,
        135,   2,  65,  15,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   8,  56,  47,  27,
        149,  63, 120,  99,  56,  22,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   2,   0,   5,  98, 170,  67,   0,
          5,  23,  18,  48,  99, 128,  52,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,  33,  73,  87,  13,  74,
        117,  33,  97, 121,  22,  91,  72,   4,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   1,   0,  12, 123,  56,  20,  33,  11,
         26,  97,  60,  11,   0,  11,  58,  40,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   1,   0,  41, 112,  97, 144,  78,  76,
         99,   6,   8,   0,  63,  91, 157, 121,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   1,   0,  63,  97, 134, 213,  13,  26,
         40, 106, 103,   0,  92, 152, 120,  92,   0,   0,   1,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   9, 133, 110,  34,  34, 105,
          6, 170, 180,  80,  13, 128,  94, 106,  15,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,  19,  97, 144, 149,  44,   0,  97,
         66,  78,  51,  65,  69, 134, 137,  51,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,  67, 156,  98, 152,  85,  42, 115,
        144,  66, 120,   6, 113, 113, 170,  45, 116,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,  69, 105,  91, 162, 116,  23, 101,
        156,  84,  29,  56, 128,  22,  85,  74, 164,   1,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,  33,  98, 127, 142, 120,  31,   4,
         42,  45,  60,  41, 141,  63,  74, 151,  67,  45,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   6, 164,  40, 142, 164, 103,  42,  95,
        124,  20, 238, 138,  62, 119, 117,  77,  36,  95,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0, 116, 126, 113, 156, 139,   0,  36,  88,
        160, 112,  42,  97,  72, 141, 171, 138,  80, 137,  42,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,  58, 115,  97, 127, 120,  26,  65,  41,
        106, 123,  77,  12,   0,   2, 131, 148, 113,  85,  56,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,  70, 126, 142, 102,  40,
         69,  66,  99,  20, 180, 112, 127, 106,   5,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0, 113, 174,   0,  90,
        113,  29,   1,  12, 137, 156,  24,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   1,   0,   4,  70,  41,  18,  77,
          5, 231, 173,  31,  81,  98,  60,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   1,   0,   9,  49,  76,  20, 134,
         40, 151,  92,  91,  58, 109,  73,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   1,   0,   0,   1,  80,  77,  16, 119,
        133,  81,  97,  52, 123,  77,  73,   0,   0,   1,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   1,   0,  36, 106, 110,  40,  92,
        167,  88,  67,  38,  98,  24,  92,   5,   0,   1,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   1,   0,   0,  77, 137,  42,  63,
        139,  84,   1, 101, 124,  85,  65,   0,   0,   2,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   2,   0,  11,  52, 156,  45,  18,
         36,  45, 131,  27, 141,  95,  91,   0,   0,   1,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   2,   0,  36, 127,  74,  73, 144,
        145,  54, 255,  85,  62, 112, 137,  22,   0,   2,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   